## _Medical Insurance Costs_

Pada kasus ini, terdapat data tentang informasi kesehatan dan biaya yang harus dikeluarkan oleh asuransi kesehatan. Infomasi terkait dengan data _medical insurance cost_ adalah sebagai berikut,

1. Age: Usia penerima manfaat
2. Sex: Gender penerima manfaat (_male_, _femele_)
3. Bmi : Body Mass Index
4. Children: Jumlah anak/tanggungan yang dicover oleh pihak asuransi
5. Smoker: Status perokok (_yes_, _no_)
6. Region: Wilayah tempat tinggal penerima manfaat
7. Charges: Biaya yang dikeluarkan oleh asuransi

In [7]:
# Selayang pandang data Medical Insurance Costs
import pandas as pd

df = pd.read_csv('data/insurance.csv')

display(df.head())

display(df.corr())

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

age       bmi  children   charges
age       1.000000  0.109272  0.042469  0.299008
bmi       0.109272  1.000000  0.012759  0.198341
children  0.042469  0.012759  1.000000  0.067998
charges   0.299008  0.198341  0.067998  1.000000

### Tantangan

Buatlah model regresi untuk memprediksi biaya yang harus dikeluarkan oleh pihak asuransi berdasarkan data. Validasi performa model regresi Anda dengan nilai ***R-squared ($R^2$)***

#### _Tasks_

1. Pastikan semua variabel kategorial diolah dengan baik. (Gunakan fitur mapping pada pandas)
2. Cek kondisi multicollinearity untuk semua variabel independen. Jika ada, antar variabel apakah itu?
3. Pastikan model menggunakan variabel yang tidak memiliki nilai multicollinearity yang tinggi
4. (Hints) Anda dapat menggunakan nilai ***Variance Inflation Factor (VIF)*** untuk mengetahui tingkat multicollinearity pada sebuah variabel independent.
5. Evaluasi model yang Anda buat dengan nilai $R^2$
6. Simpulkan, variabel independen apa saja yang dapat digunakan untuk menghasilkan model regresi yang baik pada kasus _medical insurance costs_?

#### (Hints) Interpretasi Nilai VIF

- 1 - variabel indenpenden tidak memiliki korelasi dengan variabel independen yang lain
- 1 < VIF < 5 - variabel independen sedikit memiliki korelasi dengan variabel independen yang lain
- VIF > 5 - variabel independen memiliki korelasi yang kuat dengan variabel independen lainnya
- VIF > 10 - variabel independen miliki korelasi yang sangat kuat dengan variabel independen dan perlu diperhatikan lebih lanjut

#### (Hints) Implementasi Perhitungan VIF

VIF dapat dihitung secara langsung dengan menggunakan library dari `statsmodels`

#### (Hints) Scatterplot Korelasi Antar Variabel

![var_cor](assets/var_corr.png)

In [23]:
df2 = pd.read_csv("data/insurance.csv")
df2.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

#                                                            Jawaban

1. Pastikan semua variabel kategorial diolah dengan baik. (Gunakan fitur mapping pada pandas)

In [24]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [25]:
new_labels_sex = {
    'male': 1,
    'female': 0
}

new_labels_smoker ={
    'yes' : 1,
    'no' : 0
}

new_labels_region ={
    'northwest' : 0,
    'southwest' : 1,
    'southeast' : 2,
    'northeast' : 3 
}

# Encode
df2['sex'] = df2['sex'].map(new_labels_sex)
df2['smoker'] = df2['smoker'].map(new_labels_smoker)
df2['region'] = df2['region'].map(new_labels_region)
df2.head()

age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       1  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       0  21984.47061
4   32    1  28.880         0       0       0   3866.85520

2. Cek kondisi multicollinearity untuk semua variabel independen. Jika ada, antar variabel apakah itu?
3. Pastikan model menggunakan variabel yang tidak memiliki nilai multicollinearity yang tinggi
4. (Hints) Anda dapat menggunakan nilai Variance Inflation Factor (VIF) untuk mengetahui tingkat multicollinearity pada sebuah variabel independent.

In [27]:
#pengecekan multicollonearity dengan fitur VIF untuk mengetahui tingkat multicollinearity

from statsmodels.stats.outliers_influence import variance_inflation_factor
  
X = df2[['age', 'sex' ,'bmi' ,'children', 'smoker', 'region']]
  
vif_df2 = pd.DataFrame()
vif_df2["feature"] = X.columns
  

vif_df2["VIF"] = [variance_inflation_factor(X.values, i)
                          for i in range(len(X.columns))]
  
print(vif_df2)

    feature       VIF
0       age  7.588734
1       sex  2.002652
2       bmi  9.938670
3  children  1.799980
4    smoker  1.261195
5    region  2.789478


In [29]:
df2_new = df2.copy()
df2_new.head()

age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       1  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       0  21984.47061
4   32    1  28.880         0       0       0   3866.85520

In [30]:
#penghapusan kolom "age" dan "bmi"
df2_new  = df2_new .drop(columns=['age', 'bmi'])
df2_new .head()

sex  children  smoker  region      charges
0    0         0       1       1  16884.92400
1    1         1       0       2   1725.55230
2    1         3       0       2   4449.46200
3    1         0       0       0  21984.47061
4    1         0       0       0   3866.85520

5. Evaluasi model yang Anda buat dengan nilai R2

In [49]:
X = df2_new.iloc[:, :-1].values
y = df2_new.iloc[:, 4].values

Xm_train, Xm_test, ym_train, ym_test = train_test_split(X, y, test_size=0.2, random_state=50)

In [50]:
y = y.reshape(len(y), 1)
y.shape

(1338, 1)

In [51]:
from sklearn.linear_model import LinearRegression

mlr = LinearRegression()
mlr.fit(Xm_train, ym_train)

ym_pred = mlr.predict(Xm_test)

In [52]:
con = np.concatenate((ym_test, ym_pred))
con

array([ 5976.8311    ,  5846.9176    , 13831.1152    ,  9625.92      ,
        2680.9493    , 47896.79135   , 18223.4512    ,  7419.4779    ,
        3732.6251    , 12222.8983    ,  7050.0213    , 21978.6769    ,
        6282.235     , 37701.8768    ,  7046.7222    , 12032.326     ,
       13112.6048    ,  4239.89265   , 12333.828     ,  3410.324     ,
        1727.785     , 44641.1974    , 17128.42608   ,  6112.35295   ,
        4529.477     , 10594.50155   ,  6402.29135   , 46151.1245    ,
        1711.0268    ,  1704.70015   , 45863.205     ,  4687.797     ,
       15019.76005   ,  3180.5101    ,  3861.20965   ,  3443.064     ,
       27117.99378   ,  2709.24395   , 13451.122     , 47928.03      ,
       23563.01618   ,  6710.1919    , 14235.072     , 14001.1338    ,
       27218.43725   , 13390.559     , 41034.2214    ,  2020.177     ,
       14256.1928    , 21232.18226   , 48675.5177    ,  6986.697     ,
        4149.736     , 30942.1918    ,  8023.13545   , 42124.5153    ,
      

In [53]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

X = df2_new.iloc[:, :-1]
y = df2_new.iloc[:, 4]

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.2, random_state=50)

In [54]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)

In [55]:
con = np.concatenate((y_test, y_pred))
con

array([ 5976.8311    ,  5846.9176    , 13831.1152    , ...,
       29601.16106087,  7112.16331967,  8912.12822477])

In [56]:
from sklearn.metrics import r2_score

r_square = r2_score(y_test, y_pred)
r_square

0.6060932336967906

6. Simpulkan, variabel independen apa saja yang dapat digunakan untuk menghasilkan model regresi yang baik pada kasus _medical insurance costs_?

In [57]:
X2 = df2.iloc[:, :-1].values
y2 = df2.iloc[:, 6].values

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.2, random_state=50)

In [58]:
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X2, y2, test_size=0.2, random_state=50)

In [59]:
y2 = y2.reshape(len(y), 1)
y2.shape

(1338, 1)

In [60]:
lr2 = LinearRegression()
lr2.fit(X_train_2, y_train_2)

y_pred_2 = lr2.predict(X_test_2)

In [61]:
con2 = np.concatenate((y_test_2, y_pred_2))
con2

array([ 5.97683110e+03,  5.84691760e+03,  1.38311152e+04,  9.62592000e+03,
        2.68094930e+03,  4.78967913e+04,  1.82234512e+04,  7.41947790e+03,
        3.73262510e+03,  1.22228983e+04,  7.05002130e+03,  2.19786769e+04,
        6.28223500e+03,  3.77018768e+04,  7.04672220e+03,  1.20323260e+04,
        1.31126048e+04,  4.23989265e+03,  1.23338280e+04,  3.41032400e+03,
        1.72778500e+03,  4.46411974e+04,  1.71284261e+04,  6.11235295e+03,
        4.52947700e+03,  1.05945016e+04,  6.40229135e+03,  4.61511245e+04,
        1.71102680e+03,  1.70470015e+03,  4.58632050e+04,  4.68779700e+03,
        1.50197601e+04,  3.18051010e+03,  3.86120965e+03,  3.44306400e+03,
        2.71179938e+04,  2.70924395e+03,  1.34511220e+04,  4.79280300e+04,
        2.35630162e+04,  6.71019190e+03,  1.42350720e+04,  1.40011338e+04,
        2.72184372e+04,  1.33905590e+04,  4.10342214e+04,  2.02017700e+03,
        1.42561928e+04,  2.12321823e+04,  4.86755177e+04,  6.98669700e+03,
        4.14973600e+03,  

In [62]:
r2_square_2 = r2_score(y_test_2, y_pred_2)
print(r2_square_2)

0.7835627749480736


# Kesimpulan

In [ ]:
Dari kedua hasil  dari pengecekan  4 kolom variabel indepen dan pengecekan semua 
kolom dapat disimpulkan bahwa pengecekan 4 kolom tidak lebih baik dari pengecekan semua kolom